### ISSUE TITLE
Nuget package for .net 4.8

### ISSUE THREAD

**Issue by Sicos1977** [team-charls/charls-native-dotnet#43]
Is it possible to build a c# .net framework 4.8 package? I'm stuck on that .net version.

**Comment by vbaderks** [comment]
PR #44 adds supports for .NET Framework 4.8 (pending release)

**Comment by vbaderks** [comment]
Version 3.1.0 includes support for .NET Framework 4.8: https://www.nuget.org/packages/CharLS.Native/3.1.0

**Comment by Sicos1977** [comment]
Thanks (bedankt voor het toevoegen :-)
